/**
 * Effect Schema, JSON Schema, and StandardSchema definitions for the
 * `get-a-coffee` tool input.
 *
 * @remarks
 * Defines a single source-of-truth {@link GetACoffeeInput} using
 * {@link Schema.Struct}, then derives three representations:
 *
 * | Export | Purpose |
 * |--------|------|
 * | {@link GetACoffeeInput} | Effect Schema for runtime decoding |
 * | {@link GetACoffeeInputJsonSchema} | JSON Schema for documentation / tests |
 * | {@link GetACoffeeInputStandard} | StandardSchema adapter for MCP SDK |
 *
 * @module
 */
import { JSONSchema, Schema } from "effect";
import { toStandardSchema } from "../../../../server/standard-schema-bridge.js";

/**
 * Effect Schema for validating `get-a-coffee` tool input.
 *
 * @remarks
 * Contains a single `name` field (string) identifying the coffee to
 * retrieve.  This schema is the single source-of-truth from which
 * {@link GetACoffeeInputJsonSchema} and
 * {@link GetACoffeeInputStandard} are derived.
 *
 * @example
 * ```ts
 * import { Schema } from "effect";
 * import { GetACoffeeInput } from "./get-a-coffee.schema.js";
 *
 * const decoded = Schema.decodeUnknownSync(GetACoffeeInput)({
 *   name: "Espresso",
 * });
 * // decoded: { name: "Espresso" }
 * ```
 */
export const GetACoffeeInput = Schema.Struct({ name: Schema.String });

/**
 * Inferred TypeScript type from the {@link GetACoffeeInput} schema.
 *
 * @remarks
 * Equivalent to `{ name: string }`.  Used as the parameter type for
 * `GetACoffeeService.execute` after schema validation.
 */
export type GetACoffeeInput = typeof GetACoffeeInput.Type;

/**
 * JSON Schema representation derived from {@link GetACoffeeInput}.
 *
 * @remarks
 * Generated by {@link JSONSchema.make}.  Primarily used in tests to
 * verify the schema shape (`type: "object"`, `properties.name`).
 */
export const GetACoffeeInputJsonSchema = JSONSchema.make(GetACoffeeInput);

/**
 * StandardSchema adapter bridging {@link GetACoffeeInput} to the
 * MCP SDK.
 *
 * @remarks
 * Produced by {@link toStandardSchema}.  Passed as the `inputSchema`
 * option in `registerGetACoffeeTool` so the MCP SDK can
 * validate incoming tool calls at the protocol level.
 */
export const GetACoffeeInputStandard = toStandardSchema(GetACoffeeInput);
